/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.khalicki.dynamicassertions

import com.github.khalicki.dynamicassertions.data.EmptyObject
import spock.lang.FailsWith
import spock.lang.Specification

class DynamicAssertionsAssertThatSpec extends Specification {

    @FailsWith(AssertionError.class)
    def "should fail when null is asserted"() {
        expect:
            DynamicAssertions.assertThat(null)
    }

    def "should succeed when object is not null"() {
        expect:
            DynamicAssertions.assertThat(new EmptyObject())
    }

    def "should succeed when argument is primitive"() {
        expect:
            DynamicAssertions.assertThat(42)
    }
}
